global:
  scrape_interval: 15s

rule_files:
  - alerts.yml
  - recording_rules.yml

scrape_configs:

  - job_name: village-api

    metrics_path: /metrics

    static_configs:

      - targets:
          - village-api:8080